baseURL = "http://material-design-peopleunleashed.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = ""
theme = "material-design"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "Your Disqus Name" # optional
copyright = "© 2020 Copyright Text"

[[deployment.targets]]
#An arbitrary name for this target.
name = "awsbucket"
URL = "s3://material-design-peopleunleashed/?region=us-east-1"




